version: '3.8'

services:
  mono_map:
    image: braulionavarrete/mono_map:latest
    container_name: monomap-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@mongo_new/
    depends_on:
      - mongo_new

  mongo_new:
    image: mongo
    container_name: mongo_new
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: