version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: branch_management_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - branch-network

volumes:
  mongodb_data:
    name: branch_management_volume

networks:
  branch-network:
    name: branch_management_network
    driver: bridge