version: '3.8'
services:
  branches_api:
    image: braulionavarrete/branches_api:latest
    container_name: branches_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - branch-network
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@mongodb:27017/
    
  mongodb:
    image: mongo
    container_name: branch_management_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - branch-network

volumes:
  mongodb_data:
    name: branch_management_volume

networks:
  branch-network:
    name: branch_management_network
    driver: bridge